baseURL: "https://abdus.net"
languageCode: en-us
title: Abdus S. Azad

Paginate: 10
assetDir: assets

params:
  mainSections: ["posts"]

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /self/
      weight: 3
    - identifier: daily-log
      name: daily logs
      url: "https://log.abdus.net"
      weight: 5
    - identifier: blog
      name: blog
      url: /posts/
      weight: 2
    - identifier: notes
      name: notes
      url: /notes/
      weight: 4

markup:
  tableOfContents:
    endLevel: 6
    ordered: false
    startLevel: 2
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

permalinks:
  pages: "/:filename"
  posts: "/blog/:year/:filename/"
  notes: "/notes/:filename"


disableKinds:
  - section
  - term
  - taxonomy

